// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: nzb.proto

package usenet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NZBSegment represents a segment with all necessary download info
type NZBSegmentProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Number           int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	MessageId        string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Bytes            int64                  `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	StartOffset      int64                  `protobuf:"varint,4,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset        int64                  `protobuf:"varint,5,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	Group            string                 `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	SegmentDataStart int64                  `protobuf:"varint,7,opt,name=segment_data_start,json=segmentDataStart,proto3" json:"segment_data_start,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NZBSegmentProto) Reset() {
	*x = NZBSegmentProto{}
	mi := &file_nzb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NZBSegmentProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NZBSegmentProto) ProtoMessage() {}

func (x *NZBSegmentProto) ProtoReflect() protoreflect.Message {
	mi := &file_nzb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NZBSegmentProto.ProtoReflect.Descriptor instead.
func (*NZBSegmentProto) Descriptor() ([]byte, []int) {
	return file_nzb_proto_rawDescGZIP(), []int{0}
}

func (x *NZBSegmentProto) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *NZBSegmentProto) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *NZBSegmentProto) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *NZBSegmentProto) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *NZBSegmentProto) GetEndOffset() int64 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *NZBSegmentProto) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *NZBSegmentProto) GetSegmentDataStart() int64 {
	if x != nil {
		return x.SegmentDataStart
	}
	return 0
}

// NZBFile represents a grouped file with its Segments
type NZBFileProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NzbId         string                 `protobuf:"bytes,1,opt,name=nzb_id,json=nzbId,proto3" json:"nzb_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	InternalPath  string                 `protobuf:"bytes,3,opt,name=internal_path,json=internalPath,proto3" json:"internal_path,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	StartOffset   int64                  `protobuf:"varint,5,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	Segments      []*NZBSegmentProto     `protobuf:"bytes,6,rep,name=segments,proto3" json:"segments,omitempty"`
	Groups        []string               `protobuf:"bytes,7,rep,name=groups,proto3" json:"groups,omitempty"`
	FileType      string                 `protobuf:"bytes,8,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Password      string                 `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,10,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	IsStored      bool                   `protobuf:"varint,11,opt,name=is_stored,json=isStored,proto3" json:"is_stored,omitempty"`
	SegmentSize   int64                  `protobuf:"varint,12,opt,name=segment_size,json=segmentSize,proto3" json:"segment_size,omitempty"`
	EncryptionKey []byte                 `protobuf:"bytes,13,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	EncryptionIv  []byte                 `protobuf:"bytes,14,opt,name=encryption_iv,json=encryptionIv,proto3" json:"encryption_iv,omitempty"`
	IsEncrypted   bool                   `protobuf:"varint,15,opt,name=is_encrypted,json=isEncrypted,proto3" json:"is_encrypted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NZBFileProto) Reset() {
	*x = NZBFileProto{}
	mi := &file_nzb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NZBFileProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NZBFileProto) ProtoMessage() {}

func (x *NZBFileProto) ProtoReflect() protoreflect.Message {
	mi := &file_nzb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NZBFileProto.ProtoReflect.Descriptor instead.
func (*NZBFileProto) Descriptor() ([]byte, []int) {
	return file_nzb_proto_rawDescGZIP(), []int{1}
}

func (x *NZBFileProto) GetNzbId() string {
	if x != nil {
		return x.NzbId
	}
	return ""
}

func (x *NZBFileProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NZBFileProto) GetInternalPath() string {
	if x != nil {
		return x.InternalPath
	}
	return ""
}

func (x *NZBFileProto) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *NZBFileProto) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *NZBFileProto) GetSegments() []*NZBSegmentProto {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *NZBFileProto) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *NZBFileProto) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *NZBFileProto) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *NZBFileProto) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *NZBFileProto) GetIsStored() bool {
	if x != nil {
		return x.IsStored
	}
	return false
}

func (x *NZBFileProto) GetSegmentSize() int64 {
	if x != nil {
		return x.SegmentSize
	}
	return 0
}

func (x *NZBFileProto) GetEncryptionKey() []byte {
	if x != nil {
		return x.EncryptionKey
	}
	return nil
}

func (x *NZBFileProto) GetEncryptionIv() []byte {
	if x != nil {
		return x.EncryptionIv
	}
	return nil
}

func (x *NZBFileProto) GetIsEncrypted() bool {
	if x != nil {
		return x.IsEncrypted
	}
	return false
}

// NZB represents the full NZB metadata
type NZBProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Path             string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	TotalSize        int64                  `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	DatePostedUnix   int64                  `protobuf:"varint,6,opt,name=date_posted_unix,json=datePostedUnix,proto3" json:"date_posted_unix,omitempty"`
	Category         string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Groups           []string               `protobuf:"bytes,8,rep,name=groups,proto3" json:"groups,omitempty"`
	Files            []*NZBFileProto        `protobuf:"bytes,9,rep,name=files,proto3" json:"files,omitempty"`
	Downloaded       bool                   `protobuf:"varint,10,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	AddedOnUnix      int64                  `protobuf:"varint,11,opt,name=added_on_unix,json=addedOnUnix,proto3" json:"added_on_unix,omitempty"`
	LastActivityUnix int64                  `protobuf:"varint,12,opt,name=last_activity_unix,json=lastActivityUnix,proto3" json:"last_activity_unix,omitempty"`
	Status           string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	Progress         float64                `protobuf:"fixed64,14,opt,name=progress,proto3" json:"progress,omitempty"`
	Percentage       float64                `protobuf:"fixed64,15,opt,name=percentage,proto3" json:"percentage,omitempty"`
	SizeDownloaded   int64                  `protobuf:"varint,16,opt,name=size_downloaded,json=sizeDownloaded,proto3" json:"size_downloaded,omitempty"`
	Eta              int64                  `protobuf:"varint,17,opt,name=eta,proto3" json:"eta,omitempty"`
	Speed            int64                  `protobuf:"varint,18,opt,name=speed,proto3" json:"speed,omitempty"`
	CompletedOnUnix  int64                  `protobuf:"varint,19,opt,name=completed_on_unix,json=completedOnUnix,proto3" json:"completed_on_unix,omitempty"`
	IsBad            bool                   `protobuf:"varint,20,opt,name=is_bad,json=isBad,proto3" json:"is_bad,omitempty"`
	Storage          string                 `protobuf:"bytes,21,opt,name=storage,proto3" json:"storage,omitempty"`
	FailMessage      string                 `protobuf:"bytes,22,opt,name=fail_message,json=failMessage,proto3" json:"fail_message,omitempty"`
	Password         string                 `protobuf:"bytes,23,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NZBProto) Reset() {
	*x = NZBProto{}
	mi := &file_nzb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NZBProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NZBProto) ProtoMessage() {}

func (x *NZBProto) ProtoReflect() protoreflect.Message {
	mi := &file_nzb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NZBProto.ProtoReflect.Descriptor instead.
func (*NZBProto) Descriptor() ([]byte, []int) {
	return file_nzb_proto_rawDescGZIP(), []int{2}
}

func (x *NZBProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NZBProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NZBProto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NZBProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NZBProto) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *NZBProto) GetDatePostedUnix() int64 {
	if x != nil {
		return x.DatePostedUnix
	}
	return 0
}

func (x *NZBProto) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *NZBProto) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *NZBProto) GetFiles() []*NZBFileProto {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *NZBProto) GetDownloaded() bool {
	if x != nil {
		return x.Downloaded
	}
	return false
}

func (x *NZBProto) GetAddedOnUnix() int64 {
	if x != nil {
		return x.AddedOnUnix
	}
	return 0
}

func (x *NZBProto) GetLastActivityUnix() int64 {
	if x != nil {
		return x.LastActivityUnix
	}
	return 0
}

func (x *NZBProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NZBProto) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *NZBProto) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *NZBProto) GetSizeDownloaded() int64 {
	if x != nil {
		return x.SizeDownloaded
	}
	return 0
}

func (x *NZBProto) GetEta() int64 {
	if x != nil {
		return x.Eta
	}
	return 0
}

func (x *NZBProto) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *NZBProto) GetCompletedOnUnix() int64 {
	if x != nil {
		return x.CompletedOnUnix
	}
	return 0
}

func (x *NZBProto) GetIsBad() bool {
	if x != nil {
		return x.IsBad
	}
	return false
}

func (x *NZBProto) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *NZBProto) GetFailMessage() string {
	if x != nil {
		return x.FailMessage
	}
	return ""
}

func (x *NZBProto) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_nzb_proto protoreflect.FileDescriptor

const file_nzb_proto_rawDesc = "" +
	"\n" +
	"\tnzb.proto\x12\x06usenet\"\xe4\x01\n" +
	"\x0fNZBSegmentProto\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x03R\x05bytes\x12!\n" +
	"\fstart_offset\x18\x04 \x01(\x03R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x05 \x01(\x03R\tendOffset\x12\x14\n" +
	"\x05group\x18\x06 \x01(\tR\x05group\x12,\n" +
	"\x12segment_data_start\x18\a \x01(\x03R\x10segmentDataStart\"\xe9\x03\n" +
	"\fNZBFileProto\x12\x15\n" +
	"\x06nzb_id\x18\x01 \x01(\tR\x05nzbId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rinternal_path\x18\x03 \x01(\tR\finternalPath\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12!\n" +
	"\fstart_offset\x18\x05 \x01(\x03R\vstartOffset\x123\n" +
	"\bsegments\x18\x06 \x03(\v2\x17.usenet.NZBSegmentProtoR\bsegments\x12\x16\n" +
	"\x06groups\x18\a \x03(\tR\x06groups\x12\x1b\n" +
	"\tfile_type\x18\b \x01(\tR\bfileType\x12\x1a\n" +
	"\bpassword\x18\t \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\n" +
	" \x01(\bR\tisDeleted\x12\x1b\n" +
	"\tis_stored\x18\v \x01(\bR\bisStored\x12!\n" +
	"\fsegment_size\x18\f \x01(\x03R\vsegmentSize\x12%\n" +
	"\x0eencryption_key\x18\r \x01(\fR\rencryptionKey\x12#\n" +
	"\rencryption_iv\x18\x0e \x01(\fR\fencryptionIv\x12!\n" +
	"\fis_encrypted\x18\x0f \x01(\bR\visEncrypted\"\xb4\x05\n" +
	"\bNZBProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x03R\ttotalSize\x12(\n" +
	"\x10date_posted_unix\x18\x06 \x01(\x03R\x0edatePostedUnix\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x16\n" +
	"\x06groups\x18\b \x03(\tR\x06groups\x12*\n" +
	"\x05files\x18\t \x03(\v2\x14.usenet.NZBFileProtoR\x05files\x12\x1e\n" +
	"\n" +
	"downloaded\x18\n" +
	" \x01(\bR\n" +
	"downloaded\x12\"\n" +
	"\radded_on_unix\x18\v \x01(\x03R\vaddedOnUnix\x12,\n" +
	"\x12last_activity_unix\x18\f \x01(\x03R\x10lastActivityUnix\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x0e \x01(\x01R\bprogress\x12\x1e\n" +
	"\n" +
	"percentage\x18\x0f \x01(\x01R\n" +
	"percentage\x12'\n" +
	"\x0fsize_downloaded\x18\x10 \x01(\x03R\x0esizeDownloaded\x12\x10\n" +
	"\x03eta\x18\x11 \x01(\x03R\x03eta\x12\x14\n" +
	"\x05speed\x18\x12 \x01(\x03R\x05speed\x12*\n" +
	"\x11completed_on_unix\x18\x13 \x01(\x03R\x0fcompletedOnUnix\x12\x15\n" +
	"\x06is_bad\x18\x14 \x01(\bR\x05isBad\x12\x18\n" +
	"\astorage\x18\x15 \x01(\tR\astorage\x12!\n" +
	"\ffail_message\x18\x16 \x01(\tR\vfailMessage\x12\x1a\n" +
	"\bpassword\x18\x17 \x01(\tR\bpasswordB,Z*github.com/sirrobot01/decypharr/pkg/usenetb\x06proto3"

var (
	file_nzb_proto_rawDescOnce sync.Once
	file_nzb_proto_rawDescData []byte
)

func file_nzb_proto_rawDescGZIP() []byte {
	file_nzb_proto_rawDescOnce.Do(func() {
		file_nzb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nzb_proto_rawDesc), len(file_nzb_proto_rawDesc)))
	})
	return file_nzb_proto_rawDescData
}

var file_nzb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nzb_proto_goTypes = []any{
	(*NZBSegmentProto)(nil), // 0: usenet.NZBSegmentProto
	(*NZBFileProto)(nil),    // 1: usenet.NZBFileProto
	(*NZBProto)(nil),        // 2: usenet.NZBProto
}
var file_nzb_proto_depIdxs = []int32{
	0, // 0: usenet.NZBFileProto.segments:type_name -> usenet.NZBSegmentProto
	1, // 1: usenet.NZBProto.files:type_name -> usenet.NZBFileProto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nzb_proto_init() }
func file_nzb_proto_init() {
	if File_nzb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nzb_proto_rawDesc), len(file_nzb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nzb_proto_goTypes,
		DependencyIndexes: file_nzb_proto_depIdxs,
		MessageInfos:      file_nzb_proto_msgTypes,
	}.Build()
	File_nzb_proto = out.File
	file_nzb_proto_goTypes = nil
	file_nzb_proto_depIdxs = nil
}
